import Head from 'next/head'
import Link from 'next/link'
import * as styles from '../styles/styles.css'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.themeClass}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main /*className={styles.main}*/>
          <h1 /*className={styles.title}*/>
            Welcome to <a href="https://www.imdb.com/title/tt2861424/">Rick & Morty</a> dating app!
          </h1>

          <p /*className={styles.description}*/>
            Find true love
          </p>

          <div className={styles.grid}>
            <Link href='/matchmaker/find-love'>
              <a className={styles.card}>
                <h2>Matchmaker &rarr;</h2>
                <p>Find in-depth information about your potential dates</p>
              </a>
            </Link>

            <Link href='/diary'>
              <a className={styles.card}>
                <h2>Stories &rarr;</h2>
                <p>Learn about succesfull dating experiences</p>
              </a>
            </Link>

            <Link href='/ideas'>
              <a className={styles.card} >
                <h2>Ideas &rarr;</h2>
                <p>Discover the potential romantic adventures you could experience with your future love interest.</p>
              </a>
            </Link>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>About &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>
    </div>
  )
}
